remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-include-cache

title: PowerWiz Shaggy
description: Blog om Microsoft Power Platform, Copilot & AI og Dynamics 365
author:
  name: Shahid Mahmood Hussain
  email: smh2408@gmail.com
